### ISSUE TITLE
IHaskell Kernel not connecting in Jupyter

### ISSUE THREAD

**Issue by BaseBeginner** [IHaskell/IHaskell#1374]
Hello, new user to IHaskell (and Haskell in general). As the title says, my JupyterLab can't connect to IHaskell. I followed the instructions outlined [here](https://github.com/IHaskell/IHaskell#Mac) (skipping the jupyter prerequisites). And when I do,  I see the option for Haskell among the notebooks and consoles, as shown below:

<img width="1131" alt="Screenshot 2022-10-04 at 06 38 54" src="https://user-images.githubusercontent.com/114346072/193751401-f72ec8fb-db92-4d99-85a8-cd6d9735ba7c.png">

But when attempting to open a Haskell notebook or console, the kernel fails to connect. There's no error message, it just defaults to 'No Kernel | Unknown' after a few seconds of loading.

For context, I am using a MacBook (Intel) running macOS Monterey. I have tried installing Haskell various ways: first, using GHCup. Then, haskell-stack. Then, using the binaries on [the Haskell website](https://www.haskell.org/ghc/download_ghc_9_2_4.html#macosx_x86_64).  None of that seems to make a difference. Currently, I am back to using GHCup with GHC 9.2.4.

Thanks in advance.

**Comment by vaibhavsagar** [comment]
What is the console output of running `stack exec jupyter -- notebook`?

**Comment by BaseBeginner** [comment]
Here's  the output on the terminal:

```
Last login: Tue Oct  4 07:13:39 on ttys010
kofiowusu@Kofis-MBP-2 ~ % stack exec jupyter -- notebook
[I 10:49:16.016 NotebookApp] Loading IPython parallel extension
[W 2022-10-04 10:49:17.427 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-04 10:49:17.427 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-10-04 10:49:17.434 LabApp] JupyterLab extension loaded from /usr/local/anaconda3/lib/python3.9/site-packages/jupyterlab
[I 2022-10-04 10:49:17.434 LabApp] JupyterLab application directory is /usr/local/anaconda3/share/jupyter/lab
[I 10:49:17.440 NotebookApp] The port 8888 is already in use, trying another port.
[I 10:49:17.441 NotebookApp] The port 8889 is already in use, trying another port.
[I 10:49:17.441 NotebookApp] The port 8890 is already in use, trying another port.
[I 10:49:17.441 NotebookApp] The port 8891 is already in use, trying another port.
[I 10:49:17.442 NotebookApp] The port 8892 is already in use, trying another port.
[I 10:49:17.443 NotebookApp] Serving notebooks from local directory: /Users/kofiowusu/Jupyter_Lab
[I 10:49:17.443 NotebookApp] Jupyter Notebook 6.4.8 is running at:
[I 10:49:17.443 NotebookApp] http://localhost:8823/?token=5da5f1bcd25d12fb87f91c55d092833c1b390f5a4870df00
[I 10:49:17.443 NotebookApp]  or http://127.0.0.1:8823/?token=5da5f1bcd25d12fb87f91c55d092833c1b390f5a4870df00
[I 10:49:17.443 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:49:17.449 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/kofiowusu/Library/Jupyter/runtime/nbserver-53749-open.html
    Or copy and paste one of these URLs:
        http://localhost:8823/?token=5da5f1bcd25d12fb87f91c55d092833c1b390f5a4870df00
     or http://127.0.0.1:8823/?token=5da5f1bcd25d12fb87f91c55d092833c1b390f5a4870df00


```

And then it opens a new notebook session in the browser. The Haskell kernel still does not connect though.

**Comment by BaseBeginner** [comment]
Here's an update on the terminal output, in case you find it useful. This happens after I try to create a Haskell notebook:

```

[I 10:50:38.527 NotebookApp] Kernel started: 63eb24b8-e6ef-489c-8761-ef858ebd31ac, name: haskell
[W 10:50:38.568 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20221004104915 (::1) 8.370000ms referer=http://localhost:8823/notebooks/Personal/Haskell/Untitled.ipynb
ihaskell: Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/Prelude.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/directory-1.3.6.2/System/Directory.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/unix-2.7.2.2/System/Posix/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/System/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/template-haskell-2.17.0.0/Language/Haskell/TH.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)

[I 10:50:41.526 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
ihaskell: Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/Prelude.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/directory-1.3.6.2/System/Directory.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/unix-2.7.2.2/System/Posix/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/System/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/template-haskell-2.17.0.0/Language/Haskell/TH.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)

[I 10:50:44.537 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
ihaskell: Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/Prelude.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/directory-1.3.6.2/System/Directory.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/unix-2.7.2.2/System/Posix/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/System/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/template-haskell-2.17.0.0/Language/Haskell/TH.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)

[I 10:50:47.548 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
ihaskell: Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/Prelude.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/directory-1.3.6.2/System/Directory.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/unix-2.7.2.2/System/Posix/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/System/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/template-haskell-2.17.0.0/Language/Haskell/TH.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)

[I 10:50:50.560 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
ihaskell: Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/Prelude.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/directory-1.3.6.2/System/Directory.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/unix-2.7.2.2/System/Posix/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/base-4.15.1.0/System/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /Users/kofiowusu/.stack/programs/x86_64-osx/ghc-9.0.2/lib/ghc-9.0.2/lib/../lib/x86_64-osx-ghc-9.0.2/template-haskell-2.17.0.0/Language/Haskell/TH.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)

[W 10:50:53.572 NotebookApp] KernelRestarter: restart failed
[W 10:50:53.572 NotebookApp] Kernel 63eb24b8-e6ef-489c-8761-ef858ebd31ac died, removing from map.
[W 10:51:38.544 NotebookApp] Timeout waiting for kernel_info reply from 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[E 10:51:38.546 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac)
[W 10:51:40.027 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:51:40.028 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 2.580000ms referer=None
[W 10:51:43.089 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:51:43.089 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 1.950000ms referer=None
[W 10:51:48.003 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:51:48.003 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 1.910000ms referer=None
[W 10:51:56.010 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:51:56.011 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 2.220000ms referer=None
[W 10:52:13.003 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:52:13.004 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 1.860000ms referer=None
[W 10:52:46.744 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:52:46.745 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 1.860000ms referer=None
[W 10:53:51.843 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:53:51.844 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 2.440000ms referer=None
[W 10:56:33.577 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1): Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac
[W 10:56:33.578 NotebookApp] 404 GET /api/kernels/63eb24b8-e6ef-489c-8761-ef858ebd31ac/channels?session_id=799c4d5d9abc4f00b976761a7305c8d1 (::1) 2.720000ms referer=None
[E 10:56:46.861 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/usr/local/anaconda3/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 89, in post
        yield maybe_future(km.restart_kernel(kernel_id))
      File "/usr/local/anaconda3/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/usr/local/anaconda3/lib/python3.9/asyncio/futures.py", line 201, in result
        raise self._exception
      File "/usr/local/anaconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
        result = coro.send(None)
      File "/usr/local/anaconda3/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py", line 313, in restart_kernel
        self._check_kernel_id(kernel_id)
      File "/usr/local/anaconda3/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py", line 394, in _check_kernel_id
        raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 63eb24b8-e6ef-489c-8761-ef858ebd31ac)
[E 10:56:46.870 NotebookApp] {
      "Host": "localhost:8823",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Sec-Ch-Ua": "\"Google Chrome\";v=\"105\", \"Not)A;Brand\";v=\"8\", \"Chromium\";v=\"105\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|fd7d2f5d|eff1840a1964180704ffd4c9c3680b74|1664199659",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Origin": "http://localhost:8823",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8823/notebooks/Personal/Haskell/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "_xsrf=2|fd7d2f5d|eff1840a1964180704ffd4c9c3680b74|1664199659; username-localhost-8988=\"2|1:0|10:1664228886|23:username-localhost-8988|44:MDUwNGIwN2I2NWRkNDkzZGE4NTg5YTYyZjAyZjA3MmU=|6f7bb9370c2ed78cc2ff6f969c9f247f0a49586de6e185d3cd6d1980f0d073df\"; username-localhost-8961=\"2|1:0|10:1664383086|23:username-localhost-8961|44:MzlmYjQ1NmU0NmY2NGY0ZjlmNTcwN2Q3NTI0ZTJlODg=|4ea19b31deafdccb6e14bdff83ea7672f2d543f6eb6dc6ebf791fea1f6bf9b64\"; username-localhost-8854=\"2|1:0|10:1664383798|23:username-localhost-8854|44:NDY1ZDRlYTRhMjM1NDMxZDljNDI1ZDFkNzZmNDlmNDA=|b2e9835a0edcc3a037c25eb755ebaf6c499758342bd7178e974740c503b7ecdb\"; username-localhost-8834=\"2|1:0|10:1664383872|23:username-localhost-8834|44:NzRmZmU0MzBjODIyNDczZDhiMzZmZjhiOWE4ODcxYjg=|cd12975348ae2b34ae682f202b325d4e8f6efc50164380447b3579c39cfcdcac\"; username-localhost-8915=\"2|1:0|10:1664384204|23:username-localhost-8915|44:OTQ1YmRjNGZkNTc5NGZmYTg1ZGU1YmYyMWQxYWJmMWM=|2ef57c4ca56f33da44cd93b776293ca32ba100c5689106a4ba8516c343c0edc3\"; username-localhost-8947=\"2|1:0|10:1664384309|23:username-localhost-8947|44:NDVkOTc2NzgzNDU0NDMwNzlhYmQ5OGQ3MTg5ZTI4MmE=|5a7ea631208fa949999201a9af0861225b074ea1585644099d9f400548178941\"; username-localhost-8930=\"2|1:0|10:1664385085|23:username-localhost-8930|44:NGM4ZTFkOTU3ZjQ2NDhlNGFjY2I5OTU0NzllYmYwZjA=|1b655ca9ac8cad296c43f606e470ec8e56762511ea3e9b0e47237a1e773f0857\"; username-localhost-8856=\"2|1:0|10:1664462359|23:username-localhost-8856|44:YjQ4ZDk0Y2I1NzRjNDlkYjk4ZTg3MDgzNDZkZTEwNDQ=|36844f4a8d3365afb38e72d82e08529d0e60ae50798a3802bdac7563e8bc396a\"; username-localhost-8929=\"2|1:0|10:1664866364|23:username-localhost-8929|44:NWRlY2EyOTk3MWM2NDRhYTgyOWYxN2I4OGNhZWIyMWU=|c44ed4846b7810f7ffb6afc9c81acce2cf696def867691438b3483ffada3a772\"; username-localhost-8926=\"2|1:0|10:1664866804|23:username-localhost-8926|44:YTFlZTI0MmZmNTliNGE2ZGIzMjgyMTg2M2Y0NTQ5MWM=|591549963ebe32a81bdfadd5b0de9668d24175f03d337c76da85e2b3793992e0\"; username-localhost-8837=\"2|1:0|10:1664866970|23:username-localhost-8837|44:ODQ1ZjZmZmQ2MjAyNDc5MTk0ZGViZWJjMDZjMTkwM2U=|995e39066b0fc6d29117ccbf4812a0707abc669f49a4805d1df7d32f145b92d6\"; username-localhost-8813=\"2|1:0|10:1664866979|23:username-localhost-8813|44:YWU5MWVkMTYwYmRmNDQ1Yzg2NGU5OGFiMTAwM2Y3Y2Q=|33185775346695b138dc10738f007d6a06574888af694aebb53e77eebf5e1dcd\"; username-localhost-8823=\"2|1:0|10:1664880558|23:username-localhost-8823|44:ODdjNjc1YTc2ZGQ4NDM2MGI2OGIxYTEzN2E0NjE4OTc=|0c873089003dafaae1fe596556190366116687a6aa5b5083694e347d1eb5e51f\""

```

**Comment by vaibhavsagar** [comment]
This error usually indicates that the GHC version you used to install IHaskell is different from your system GHC version, as described in https://github.com/IHaskell/IHaskell#the-kernel-keeps-dying-ihaskell--stack.

**Comment by BaseBeginner** [comment]
Okay.... some progress, I think.

I uninstalled ghc 9.2.4 with ghcup and installed and set ghc 9.0.2, since I guessed that that's the version IHaskell is using from the error messages. And now when I launch Jupyter from the Notebook app, I can connect to Haskell. However, it still fails when I launch JupyterLab from the JupyterLab app/icon. And the latter is the only way (that I know of) to run Jupyter kernels as consoles (which I use quite frequently).

Some screenshots to illustrate my situation:

My Anaconda setup with the 2 different apps:

<img width="1041" alt="Screenshot 2022-10-05 at 02 01 34" src="https://user-images.githubusercontent.com/114346072/193970528-e2eb4c8f-6f5f-4fb3-9a29-88f5b031cfff.png">


A Haskell notebook launched from Jupyter Notebook (successfully connects to kernel):

<img width="1513" alt="Screenshot 2022-10-05 at 02 03 08" src="https://user-images.githubusercontent.com/114346072/193970514-3cbd555a-6694-426c-9099-b6ebb106a814.png">

<img width="1515" alt="Screenshot 2022-10-05 at 02 03 49" src="https://user-images.githubusercontent.com/114346072/193970553-78abe2e0-ae66-4f08-a847-6806b0ec6fca.png">

A Jupyter Notebook session:

<img width="1505" alt="Screenshot 2022-10-05 at 02 05 35" src="https://user-images.githubusercontent.com/114346072/193970607-bf6e214e-1a5a-4c60-82f2-4ab8e4e4afa8.png">

Notebook from a Jupyter Notebook session:

<img width="1505" alt="Screenshot 2022-10-05 at 02 07 38" src="https://user-images.githubusercontent.com/114346072/193970667-d93c0b30-1a05-4eac-ab0a-4cc9b17ce7a1.png">

Console from a Jupyter Notebook session:

<img width="1505" alt="Screenshot 2022-10-05 at 02 09 38" src="https://user-images.githubusercontent.com/114346072/193970737-4d1c90e1-4ae2-48db-b4e2-fe96100cc4cc.png">

**Comment by vaibhavsagar** [comment]
Are you still getting the same console output as before? These screenshots aren't helpful for debugging since they don't indicate what is going wrong.

**Comment by BaseBeginner** [comment]
There is no console output (that I can see) when I open Jupyter from the Notebook app. It just opens up JupyterLab. Sorry.


EDIT:

Okay, this is interesting. So I just discovered there's a command to open JupyterLab from the terminal (`jupyter lab`). And when I open JupyterLab that way I can connect Haskell to both the console and the notebooks. So it seems the only problem is connecting to Haskell when opening JupyterLab from the GUI (Notebook app). 

Honestly, right now, my main problem is functionally solved - I can now use Haskell in JupyterLab in the ways I want. I _would_ like to fix the issue of opening JupyterLab from the GUI (to simplify my workflow and to understand what's happening) but I understand if you're not motivated enough to continue helping me. In either case, thanks for the help you've already given. It's been a great help.
