### ISSUE TITLE
ihaskell-widgets Plotting UI.ipynb Failed to load model class 'HBoxModel'

### ISSUE THREAD

**Issue by jamesdbrock** [IHaskell/IHaskell#1380]
__`Plotting UI.ipynb`__

<dl>
<dt><code>[13]</code></dt>
<dd><pre>
-- Spurious update to display empty plot instead of empty image initially
update return

divBox
</pre></dd>
<dt></dt>
<dd><pre>[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'HBoxModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.4.0 is not registered, however,         2.0.0 is
    at f.loadClass (http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:74977)
    at f.loadModelClass (http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:10729)
    at f._make_model (http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:7517)
    at f.new_model (http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:5137)
    at f.handle_comm_open (http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:3894)
    at _handleCommOpen (http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:73393)
    at KernelConnection._handleCommOpen (http://127.0.0.1:8888/static/lab/jlab_core.e37126dc66509a1e278e.js:70541:19)
    at async KernelConnection._handleMessage (http://127.0.0.1:8888/static/lab/jlab_core.e37126dc66509a1e278e.js:70709:25)</pre>
</dl>

**Comment by jamesdbrock** [comment]
Darn, it looks like this error is happening for all of the __ihaskell-widgets__ now.

**Comment by jamesdbrock** [comment]
https://www.npmjs.com/package/@jupyter-widgets/controls

This is for 

```
(base) jovyan@79015b09e228:~$ jupyter labextension list
JupyterLab v3.0.16
/home/jovyan/.local/share/jupyter/labextensions
        jupyterlab-ihaskell v0.0.14 enabled OK

/opt/conda/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v5.0.3 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
```

```
(base) jovyan@79015b09e228:~$ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hf3d152e_0    conda-forge
jupyter_server            1.8.0              pyhd8ed1ab_0    conda-forge
jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
jupyterhub                1.4.1            py39hf3d152e_0    conda-forge
jupyterhub-base           1.4.1            py39hf3d152e_0    conda-forge
jupyterlab                3.0.16             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.6.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
```

**Comment by jamesdbrock** [comment]
https://github.com/IHaskell/IHaskell/blob/7d0b9b070aa821db1a4d38826e146fd2c41d1c0b/ihaskell-display/ihaskell-widgets/MsgSpec.md

> The model implemented is the Model State v8, for ipywidgets 7.4., @jupyter-widgets/base 1.1., and @jupyter-widgets/controls 1.4.*.

**Comment by jamesdbrock** [comment]
Ah this must be the culprit

https://github.com/IHaskell/IHaskell/blob/7d0b9b070aa821db1a4d38826e146fd2c41d1c0b/ihaskell-display/ihaskell-widgets/src/IHaskell/Display/Widgets/Types.hs#L565-L571

**Comment by jamesdbrock** [comment]
The ipywidgets changelog has better information. https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md

**Comment by jamesdbrock** [comment]
Ok, the problem was that I was using [ipywidgets v8.0](https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md#80). When I downgrade to [ipywidgets v7.7.1](https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md#771) then the __ihaskell-widgets__ work fine.
